#!/usr/bin/env bash
set -euxo pipefail

BENCH="tests/bench-radar"
STAGE2="build/release/stage2"
STAGE3="build/release/stage3"

# Build previous stages and warm up stage3
cmake --preset release
timeout -s KILL 1h time make -C build/release -j"$(nproc)" stage3
find "$STAGE3" -name "*.olean" -delete

# Substitute our own wrapper script
mv "$STAGE2/bin/lean" "$STAGE2/bin/lean.wrapped"
cp "$BENCH/stdlib/lean_wrapper.py" "$STAGE2/bin/lean"

# Build stage3
"$BENCH/measure.py" -t stdlib \
  -m instructions -m maxrss -m task-clock -m wall-clock -- \
  lakeprof record make -C build/release -j"$(nproc)" stage3

# Analyze lakeprof data
lakeprof report -pj | jq -r '"radar::measurement=\({metric: "stdlib/lakeprof/longest build path//wall-clock", value: .[-1][2], unit: "s"})"'
lakeprof report -rj | jq -r '"radar::measurement=\({metric: "stdlib/lakeprof/longest rebuild path//wall-clock", value: .[-1][2], unit: "s"})"'
